# ~/.config/alacritty/alacritty.toml

general.import = [
  "/Users/robertwilliamson/.nvm/versions/node/v21.7.1/lib/node_modules/alacritty-themes/themes/Catppuccin-Mocha.toml"
]

[font]
size = 15

[font.normal]
family = "DejaVuSansM Nerd Font Mono"

[font.bold]
family = "DejaVuSansM Nerd Font Mono"

[font.italic]
family = "DejaVuSansM Nerd Font Mono"

[keyboard]
bindings = [
  { key = "F",     mods = "Alt", action = "ToggleSimpleFullscreen" },
  { key = "Q",     mods = "Command",  action = "None" },
  { key = "Right",  mods = "Alt", chars = "\u001BF" },
  { key = "Left",   mods = "Alt", chars = "\u001BB" },
]

[window]
opacity = 0.6
decorations = "Buttonless"
dynamic_padding = true

[mouse]
hide_when_typing = true

[colors]
transparent_background_colors = true
